export const MAIN_MENU_WIDTH_MOBILE = 16 * 11;
export const MAIN_MENU_WIDTH_DESKTOP = MAIN_MENU_WIDTH_MOBILE * 2;
export const MIN_GAME_WIDTH_DESKTOP = 640;
export const MIN_GAME_HEIGHT_DESKTOP = 480;
export const MIN_GAME_WIDTH_MOBILE = 384;
export const GAME_HEIGHT_TO_WIDTH_PROPORTION = 1.3;
